### PR TITLE
add three more urls

### PR DESCRIPTION
**Pull request by robkam**

### CODE REVIEW

**Comment by nemobis** [comment]
Thank you. We'd prefer not to update the lists with thousands of patches 
containing a handful URLs each. Can you get the sysadmins to send us a 
complete list of the current public wikis, like the last time?

**Comment by robkam** [comment]
[Requested on the Stewards' noticeboard ](https://meta.miraheze.org/wiki/Stewards%27_noticeboard#Please_send_a_list_of_all_public_wikis_to_WikiTeam)

**Comment by dmehus** [comment]
This is my first contribution to GitHub, and I'm _not_ a Miraheze volunteer staff member; just a community volunteer (like @robkam). As I said on the above-linked Stewards' noticeboard page, would the https://meta.miraheze.org/wiki/Special:WikiDiscover special page not work? Selecting "uncategorised" lists all wikis, public and private, and their status (open, inactive, and closed), regardless of how they're categorised.

**Comment by robkam** [comment]
Unfortunately that page is the entry to multiple lists, from there it would require too much fiddling about to get a single list of all public wikis in all languages. I'm sure there's a simpler way.

**Comment by RhinosF1** [comment]
> Thank you. We'd prefer not to update the lists with thousands of patches containing a handful URLs each. Can you get the sysadmins to send us a complete list of the current public wikis, like the last time?

I've made a simple python script to do this

**Comment by RhinosF1** [comment]
Replaced with #386

**Comment by dmehus** [comment]
@RhinosF1 Nice! That'll be great for updating the list from time to time.

**Comment by RhinosF1** [comment]
@dmehus: It was the easiest way to generate it anyway!

**Pull request closed without merging**
