### PR TITLE
Resume and list titles without keeping everything in memory

### PR DESCRIPTION
**Pull request by nemobis**

### CODE REVIEW

**Comment by nemobis** [comment]
Ready for review, has https://github.com/WikiTeam/wikiteam/pull/224 as parent (mainly for ease of testing).

This breaks resuming for Windows, I guess. Do we know if anything works on Windows at all, or if we have any Windows user doing larger dumps? I'm not going to work more on this now, I/we can find a better solution later.

**Comment by nemobis** [comment]
Hm, I see `ed` consuming 2 GB of memory to remove less than 50 lines. Clearly it's not as efficient as I thought. `ex` (elvis 2.2.0) seems to behave better.

**Comment by nemobis** [comment]
Nope, that doesn't work well either. elvis is better at memory, but after 10 hours CPU time I'm still not seeing an end for some GB-big dumps. :(

**Comment by nemobis** [comment]
"This pull request can be automatically merged." :)

**Comment by PiRSquared17** [comment]
This is much better than the current version, but would something like @mrshu suggested on #234 be possible?

**Comment by nemobis** [comment]
PiRSquared17, 30/03/2015 00:14:
> This is much better than the current version, but would something like
> @mrshu <https://github.com/mrshu> suggested on #234
> <https://github.com/WikiTeam/wikiteam/pull/234> be possible?

I have no idea how. Calculating the file offset requires reading the 
entire file, AFAICS.

**Comment by PiRSquared17** [comment]
@nemobis : Before you append to the dump file, store the current position (either use tell() or increment an index) in a metadata file. Then when you want to find the beginning of the last page, it's trivial (just seek(n)).

**Comment by nemobis** [comment]
But then you would be relying on the metadata file containing the correct information, while anything might have happened after the last time it was updated.

**Comment by PiRSquared17** [comment]
I see your point. (But I don't know exactly what could mess up the dump that the metadata file is useless. I'm sure it's possible...)

I'm fine with merging this.

**Comment by nemobis** [comment]
Ok, *now* it actually works, as far as I can see. Tested by `tail`ing before and after the reverse_readline() call on a dozen Wikia dumps, but they were all ending with `</page>` already so they might not be representative. Please test.

I still got a MemoryError in one case but I couldn't see in which line it happened; it's unrelated from this change though.

**Comment by nemobis** [comment]
Ah, but if the <page> or </page> got removed incorrectly the final count should reveal that, and the dump will be restarted. Hopefully no erroneous dumps coming from that.

**Comment by nemobis** [comment]
> I'm fine with merging this.

Thanks, let's continue from here.

**Pull request merged**
