### PR TITLE
Wikia dumps now use 7z, not gz

### PR DESCRIPTION
**Pull request by nemobis**
Note that existence doesn't mean the dump is usable.

### CODE REVIEW

**Comment by emijrp** [comment]
Is Wikia offering dumps? I checked one wiki and dump link was broken.

**Comment by nemobis** [comment]
Emilio, 16/05/2018 22:29:
> Is Wikia offering dumps? I checked one wiki and dump link was broken.

Yes, there are dumps, but most are broken.

**Comment by emijrp** [comment]
Small wikis too? Or big ones are broken? Current only or full history?

**Comment by nemobis** [comment]
Emilio, 16/05/2018 22:35:
> Small wikis too? Or big ones are broken? Current only or full history?

The bigger the dump, the more likely it's broken.

We could add an extra check which downloads the 7z file, `7z e -so` it 
and verifies that the trailing </mediawiki> exists.

**Comment by nemobis** [comment]
This one for instance seems ok:
http://lotr.wikia.com/wiki/Special:Statistics

**Comment by nemobis** [comment]
Actually, just checking well-formedness doesn't help. http://s3.amazonaws.com/wikia_xml_dumps/o/on/onepiece_pages_full.xml.7z has a closing </mediawiki>, but only contains 38477 revisions for 82 pages, out of 1490k and 263k.

**Pull request merged**
