### PR TITLE
Update miraheze.org list

### PR DESCRIPTION
**Pull request by RhinosF1**
Using https://gist.github.com/RhinosF1/18c83dfbfadb84e28ee083628c029b41

### CODE REVIEW

**Comment by nemobis** [comment]
Thanks. Please add the script you used as well, naming it miraheze.py.

**Comment by RhinosF1** [comment]
@nemobis: In which folder?

**Comment by robkam** [comment]
> @nemobis

**Comment by nemobis** [comment]
This same folder, you can replace miraheze-spider.py if that doesn't 
work any more.

Federico

**Pull request merged**
